### ISSUE TITLE
Support the ability to specify a proxy

### ISSUE THREAD

**Issue by dparpyani** [philnash/pwned#21]
Currently, it seems that the only way to specify a proxy is to use the http_proxy environment variable. Net::HTTP looks for this variable, unless one is explicitly passed in to the call to `Net::HTTP.new` or `Net::HTTP.start`.

Unfortunately, this does not work well if you only want to specify a proxy for the pwned gem, without affecting other net-http connections in an app. Is there a plan to support passing the proxy during initialization or via some other way?

**Comment by philnash** [comment]
I had no plans for it myself, but I'll happily take pull requests for this feature, if it's something you need.

**Comment by dparpyani** [comment]
Great, thanks! I'll open one in a bit.

**Comment by philnash** [comment]
Thanks for the PR. It was merged and released as [version 2.2.0](https://rubygems.org/gems/pwned/versions/2.2.0).
