### ISSUE TITLE
Not using https_proxy from the OS

### ISSUE THREAD

**Issue by jannamamer** [philnash/pwned#23]
It seems like the gem is not picking up the `https_proxy` set from the OS and we need to explicitly set it for every request. Is there a way to recognize the `https_proxy` environment variable set from the OS?

**Comment by dylan-hoefsloot** [comment]
This issue can be closed

**Comment by philnash** [comment]
Indeed! As of version 2.3.0 the gem [will pick up the `https_proxy` from the environment](https://github.com/philnash/pwned#http-proxy).
