### ISSUE TITLE
Support for Pwned API v3

### ISSUE THREAD

**Issue by basex** [philnash/pwned#29]
Documentation: https://haveibeenpwned.com/api/v3

**Comment by tvanderpol** [comment]
I like this gem and the pwned service so I figured I'd have a look - the end point is [identical](https://haveibeenpwned.com/api/v3#SearchingPwnedPasswordsByRange) and as far as I can see, the behaviour is completely unchanged.

**Comment by philnash** [comment]
Thanks for being proactive @basex and thanks for looking into it @tvanderpol. As far as I understand the Pwned Passwords section of the Have I Been Pwned API has not changed between v2 and v3, so there's no work needed for this gem.

I'll close this for now, but let me know if I've misunderstood something.

**Comment by basex** [comment]
Sorry, I was not aware it was using only that endpoint.

Either way, I suggest a small update to the documentation since it explicitly says v2: https://github.com/philnash/pwned/pull/30

**Comment by philnash** [comment]
Reopened, that's a good idea, thanks!

**Comment by philnash** [comment]
@basex I'm about to get on a plane, would love it if you were able to contribute a PR to make this more obvious.

**Comment by philnash** [comment]
I've merged the PR, thanks again for noticing this and updating it!
